version: '3.7'
services:
  postgres:
    image: postgres
    container_name: "postgres"
    ports:
      - '5432:5432'
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=app
    restart: always

  mysql:
    image: mysql
    container_name: "mysql"
    ports:
      - '3306:3306'
    volumes:
      - ./data/mysql/:/var/lib/mysql
    environment:
      - MYSQL_USER=app
      - MYSQL_PASSWORD=pass
      - MYSQL_ROOT_PASSWORD=pass
      - MYSQL_DATABASE=app
    restart: always

  gate:
    container_name: gate
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - '9999:9999'
    restart: always